### Create a new Skill
POST http://localhost:5169/api/skills
Content-Type: application/json

{
  "name": "Comfortable with Linux CLI",
  "description": "Learn basic bash commands, file navigation, and permissions.",
  "status": 0
}

### Get all Skills
GET http://localhost:5169/api/skills


### Link Skill 2 as a prerequisite to Skill 1
POST http://localhost:5169/api/skills/1/prerequisites
Content-Type: application/json